package data.Lobby;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.parsing.Parser;
import org.junit.jupiter.api.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

/**
 * REST Assured test suite for LobbyController endpoints.
 * Tests lobby creation, retrieval, updates, and deletion operations.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class ColtenSystemTest {

    @LocalServerPort
    private int port;

    private String testJoinCode;
    private long testLobbyId;

    @BeforeAll
    public void setup() {
        RestAssured.port = port;
        RestAssured.baseURI = "http://localhost";

        // Treat text/plain responses as JSON
        RestAssured.registerParser("text/plain", Parser.JSON);
    }

    /**
     * Test Case 1: Create a lobby with auto-generated join code and verify it's created correctly
     * Tests POST /Lobby/joinCode/autogen/{username}
     *
     * This test verifies:
     * - A lobby can be created with an auto-generated 4-digit join code
     * - The join code is unique and within the expected range (1000-9999)
     * - The host user is properly added to the lobby
     * - The lobby can be retrieved by the generated join code
     */
    @Test
    @Order(1)
    public void testCreateLobbyWithAutogeneratedJoinCodeAndVerifyCreation() {
        // First, create a test user (assuming you have a user creation endpoint)
        // If not, this test assumes "testUser1" already exists in your database

        // Create lobby with auto-generated join code
        testJoinCode = given()
                .contentType(ContentType.JSON)
                .body("{\"gameType\": \"BLACKJACK\"}")
                .when()
                .post("/Lobby/joinCode/autogen/testUser1")
                .then()
                .statusCode(200)
                .body(notNullValue())
                .body(matchesPattern("\\d{4}")) // Verify it's a 4-digit code
                .extract()
                .asString();

        System.out.println("Generated join code: " + testJoinCode);

        // Verify the lobby was created and can be retrieved
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .statusCode(200)
                .body("joinCode", equalTo(testJoinCode))
                .body("gameType", equalTo("BLACKJACK"))
                .body("users", hasSize(1))
                .body("users[0].username", equalTo("testUser1"))
                .body("lobbyID", notNullValue());

        // Store the lobby ID for later tests
        Number lobbyIdNumber = given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .extract()
                .path("lobbyID");

        testLobbyId = lobbyIdNumber.longValue();
    }

    /**
     * Test Case 2: Test adding and removing users from a lobby via join code
     * Tests PUT /Lobby/joinCode/{joinCode}/{username}
     *
     * This test verifies:
     * - Multiple users can be added to the same lobby
     * - The user count increases correctly
     * - Calling the endpoint again removes the user (toggle behavior)
     * - The user count decreases when a user is removed
     * - Success/failure messages are returned appropriately
     */
    @Test
    @Order(2)
    public void testAddAndRemoveMultipleUsersFromLobbyByJoinCode() {
        // Verify initial state (should have 1 user from previous test)
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .body("users", hasSize(1));

        // Add second user to the lobby
        given()
                .pathParam("joinCode", testJoinCode)
                .pathParam("username", "testUser2")
                .when()
                .put("/Lobby/joinCode/{joinCode}/{username}")
                .then()
                .statusCode(200)
                .body("message", equalTo("success"));

        // Verify second user was added
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .body("users", hasSize(2))
                .body("users.username", hasItems("testUser1", "testUser2"));

        // Add third user
        given()
                .pathParam("joinCode", testJoinCode)
                .pathParam("username", "testUser3")
                .when()
                .put("/Lobby/joinCode/{joinCode}/{username}")
                .then()
                .statusCode(200)
                .body("message", equalTo("success"));

        // Verify all three users are in the lobby
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .body("users", hasSize(3))
                .body("users.username", hasItems("testUser1", "testUser2", "testUser3"));

        // Remove testUser2 (toggle behavior - calling again removes)
        given()
                .pathParam("joinCode", testJoinCode)
                .pathParam("username", "testUser2")
                .when()
                .put("/Lobby/joinCode/{joinCode}/{username}")
                .then()
                .statusCode(200)
                .body("message", equalTo("success"));

        // Verify testUser2 was removed
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .body("users", hasSize(2))
                .body("users.username", hasItems("testUser1", "testUser3"))
                .body("users.username", not(hasItem("testUser2")));
    }

    /**
     * Test Case 3: Test filtering lobbies by game type
     * Tests GET /Lobby/GameType/{gameType}
     *
     * This test verifies:
     * - Multiple lobbies with different game types can be created
     * - The filter endpoint returns only lobbies matching the requested game type
     * - Lobbies with different game types are excluded from results
     * - The endpoint handles all valid GameType enum values
     */
    @Test
    @Order(3)
    public void testFilterLobbiesByGameTypeReturnsOnlyMatchingLobbies() {
        // Create a second lobby with a different game type (GO_FISH)
        String goFishJoinCode = given()
                .contentType(ContentType.JSON)
                .body("{\"gameType\": \"GO_FISH\"}")
                .when()
                .post("/Lobby/joinCode/autogen/testUser4")
                .then()
                .statusCode(200)
                .extract()
                .asString();

        // Create a third lobby with EUCHRE game type
        String euchreJoinCode = given()
                .contentType(ContentType.JSON)
                .body("{\"gameType\": \"EUCHRE\"}")
                .when()
                .post("/Lobby/joinCode/autogen/testUser5")
                .then()
                .statusCode(200)
                .extract()
                .asString();

        // Filter by BLACKJACK - should return at least our test lobby
        given()
                .pathParam("gameType", "BLACKJACK")
                .when()
                .get("/Lobby/GameType/{gameType}")
                .then()
                .statusCode(200)
                .body("$", not(empty()))
                .body("gameType", everyItem(equalTo("BLACKJACK")))
                .body("findAll { it.joinCode == '" + testJoinCode + "' }", hasSize(1));

        // Filter by GO_FISH - should return the GO_FISH lobby
        given()
                .pathParam("gameType", "GO_FISH")
                .when()
                .get("/Lobby/GameType/{gameType}")
                .then()
                .statusCode(200)
                .body("$", not(empty()))
                .body("gameType", everyItem(equalTo("GO_FISH")))
                .body("findAll { it.joinCode == '" + goFishJoinCode + "' }", hasSize(1))
                .body("joinCode", not(hasItem(testJoinCode))); // Should NOT contain BLACKJACK lobby

        // Filter by EUCHRE
        given()
                .pathParam("gameType", "EUCHRE")
                .when()
                .get("/Lobby/GameType/{gameType}")
                .then()
                .statusCode(200)
                .body("gameType", everyItem(equalTo("EUCHRE")))
                .body("findAll { it.joinCode == '" + euchreJoinCode + "' }", hasSize(1));

        // Clean up the additional lobbies
        given()
                .pathParam("joinCode", goFishJoinCode)
                .when()
                .delete("/Lobby/joinCode/{joinCode}");

        given()
                .pathParam("joinCode", euchreJoinCode)
                .when()
                .delete("/Lobby/joinCode/{joinCode}");
    }

    /**
     * Test Case 4: Test complete lobby lifecycle - update game type, then delete
     * Tests PUT /Lobby/joinCode/{joinCode} and DELETE /Lobby/joinCode/{joinCode}
     *
     * This test verifies:
     * - A lobby's game type can be updated successfully
     * - The update persists when retrieving the lobby
     * - A lobby can be deleted by its join code
     * - After deletion, the lobby cannot be retrieved (404 or null)
     * - User relationships are properly cleaned up on deletion
     */
    @Test
    @Order(4)
    public void testUpdateLobbyGameTypeThenDeleteAndVerifyCleanup() {
        // Verify initial state
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .body("gameType", equalTo("BLACKJACK"));

        // Update the lobby's game type to GO_FISH
        given()
                .contentType(ContentType.JSON)
                .pathParam("joinCode", testJoinCode)
                .body("{\"gameType\": \"GO_FISH\"}")
                .when()
                .put("/Lobby/joinCode/{joinCode}")
                .then()
                .statusCode(200)
                .body("message", equalTo("success"));

        // Verify the game type was updated
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .statusCode(200)
                .body("gameType", equalTo("GO_FISH"))
                .body("joinCode", equalTo(testJoinCode));

        // Update to EUCHRE to test multiple updates
        given()
                .contentType(ContentType.JSON)
                .pathParam("joinCode", testJoinCode)
                .body("{\"gameType\": \"EUCHRE\"}")
                .when()
                .put("/Lobby/joinCode/{joinCode}")
                .then()
                .statusCode(200)
                .body("message", equalTo("success"));

        // Verify second update
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .body("gameType", equalTo("EUCHRE"));

        // Now delete the lobby
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .delete("/Lobby/joinCode/{joinCode}")
                .then()
                .statusCode(200)
                .body("message", equalTo("success"));

        // Verify the lobby no longer exists (should return null or 404)
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .get("/Lobby/joinCode/{joinCode}")
                .then()
                .body(anyOf(
                        nullValue(),
                        emptyOrNullString()
                ));

        // Try to delete again - should fail since it doesn't exist
        given()
                .pathParam("joinCode", testJoinCode)
                .when()
                .delete("/Lobby/joinCode/{joinCode}")
                .then()
                .statusCode(200)
                .body("message", equalTo("failure"));
    }

    /**
     * Cleanup method to ensure test data doesn't pollute the database
     */
    @AfterAll
    public void cleanup() {
        // Attempt to clean up any remaining test lobbies
        if (testJoinCode != null) {
            try {
                given()
                        .pathParam("joinCode", testJoinCode)
                        .when()
                        .delete("/Lobby/joinCode/{joinCode}");
            } catch (Exception e) {
                // Ignore if already deleted
            }
        }

        // Delete empty lobbies
        given()
                .when()
                .delete("/Lobby/empty");
    }
}